package org.sat4j.scala
import scala.collection._
import org.sat4j.scala.Logic._

abstract class Literal(val id: Int) {
  def unary_!():Literal
}

case class PositiveLiteral(override val id: Int) extends Literal(id) {
  def unary_!() = NegativeLiteral(this.id)
}

case class NegativeLiteral(override val id: Int) extends Literal(id){
  def unary_!() = PositiveLiteral(this.id)
}

/** Base class for constraints making up a flat constraint system */
abstract class FlatConstraint

/** A clause.*/
class FlatClause(literals: Literal*) extends FlatConstraint

/** An 'at most' cardinality constraint. */
class FlatAtMost(literals: List[Literal], k:Int) extends FlatConstraint

/** An 'at least' cardinality constraint. */
class FlatAtLeast(literals: List[Literal], k:Int) extends FlatConstraint

/** An 'exaxt' cardinality constraint. */
class FlatCardExact(literals: List[Literal], k:Int) extends FlatConstraint

/** Allows to flatten a BoolExp to a list of clauses and cardinality constraints.
 * 
 * */
class Flattener {
  
	/** A cache which stores the translation of expressions. */
	val boolExpCache = new mutable.OpenHashMap[BoolExp, Literal]()
	
	/** Map storing the literals associated with BoolExp identifiers */
	val identifierCache = new mutable.OpenHashMap[Identifier, Literal]()

	/** All constraints generated by the flattening */
	val constraints = new mutable.ArrayStack[FlatConstraint]()
	
	/** PositiveLiteral represents True */
	constraints += new FlatClause(PositiveLiteral(0))

	/** Global Literal id counter */
	var gid = 0
	
	/** Returns a new literal */
	private[this] def newLiteral = {
	  gid += 1
	  PositiveLiteral(gid)
	} 

	/** Returns a literal encoding the given expression.
	 *  Constraints are created by side effect and stored in the flattener.
	 * */
	def apply(e: BoolExp):Literal = boolExpCache.getOrElseUpdate(e, _translate(e))

	private[this] def _translate(e: BoolExp):Literal = e match {
	  case True => {
		  PositiveLiteral(0)
	  }
	  case False => {
		  NegativeLiteral(0)
	  }
	  case ident@Ident(s) => {
		  val x = newLiteral
		  identifierCache.+=(ident -> x)
		  x
	  }
	  case ident@IndexedIdent(s, l) => {
		  val x = newLiteral
		  identifierCache.+=(ident -> x)
		  x
	  }
	  case Not(Not(l)) => {
		  apply(l)
	  }
	  case Not(l) => {
		  !apply(l)
	  }
	  
	  case And(False, _) => apply(False)
	  case And(_, False) => apply(False)
	  case And(True, r) => apply(r)
	  case And(l, True) => apply(l)
	  
	  case And(l, r) => {
		  val x = newLiteral
		  val tl = apply(l)
		  val tr = apply(r)
		  constraints += new FlatClause(x, !tl, !tr)
		  constraints += new FlatClause(!x, tl)
		  constraints += new FlatClause(!x, tr)
		  x
	  }

	  case Or(False, r) => apply(r)
	  case Or(l, False) => apply(l)
	  case Or(True, _) => apply(True)
	  case Or(_, True) => apply(True)
	  
	  case Or(l, r) => {
		  val x = newLiteral
		  val tl = apply(l)
		  val tr = apply(r)
		  constraints += new FlatClause(!x, tl, tr)
		  constraints += new FlatClause(x, !tl)
		  constraints += new FlatClause(x, !tr)
		  x
	  }

	  case Implies(False, _) => apply(True)
	  case Implies(True, r) => apply(r)
	  case Implies(l, False) => apply(Not(l))
	  
	  case Implies(l, r) => {
		  val x = newLiteral
		  val tl = apply(l)
		  val tr = apply(r)
		  constraints += new FlatClause(!x, !tl, tr)
		  constraints += new FlatClause(x, tl)
		  constraints += new FlatClause(x, !tr)
		  x
	  }
	  
	  case Iff(True, r) => apply(r)
	  case Iff(False, r) => apply(Not(r))
	  case Iff(l, True) => apply(l)
	  case Iff(l, False) => apply(Not(l))
	  case Iff(l, r) => {
		  val x = newLiteral
		  val tl = apply(l)
		  val tr = apply(r)
		  constraints += new FlatClause(!x, !tl, tr)
		  constraints += new FlatClause(!x, tl, !tr)
		  constraints += new FlatClause(x, tl, tr)
		  constraints += new FlatClause(x, !tl, !tr)
		  x
	  }
	  
	  case CardEQ(es, k) => apply(And(CardLE(es,k), CardGE(es,k)))

	  /*
	   *  x1 + ... + xn <= k equivalent to literal x with
	   * (x + ...(k+1 times)... + x)  + x1 + ... + xn >= k+1
	   * (x + ...(n times)... + x)  + x1 + ... + xn <= n + k
	   */
	  case CardLE(es, k) => {
		  val x = newLiteral
		  val n = es.size
		  val kp1x = (1 to k+1).toList map { _ => x }
		  val nx = (1 to n).toList map { _ => x }
		  val tes = es map { apply }
		  constraints += new FlatAtLeast(tes.reverse_:::(kp1x), k + 1)
		  constraints += new FlatAtMost(tes.reverse_:::(nx), n + k )
		  x
	  }

	  case CardLT(es, k) => apply(CardLE(es, k-1))
	  
	  /*
	   *  x1 + ... + xn >= k equivalent to literal x with
	   * (!x + ...(k times)... + !x)  + x1 + ... + xn >= k
	   * (!x + ...(n times)... + !x)  + x1 + ... + xn <= n + k - 1
	   */
	  case CardGE(es, k) => {
		  val x = newLiteral
		  val n = es.size
		  val kx = (1 to k).toList map { _ => !x }
		  val nx = (1 to n).toList map { _ => !x }
		  val tes = es map { apply }
		  constraints += new FlatAtLeast(tes.reverse_:::(kx), k)
		  constraints += new FlatAtMost(tes.reverse_:::(nx), n + k - 1)
		  x
	  }
	  case CardGT(es, k) => apply(CardGE(es, k+1))
	} 
}